### ISSUE TITLE
Write Documentation regarding deployment in vercel

### ISSUE THREAD

**Issue by Showrin** [Showrin/nextjs-tailwind-storybook-with-ci-cd#8]
## Description
We can deploy our nextjs app on various platforms; **Vercel** is one of them. Our goal is to guide users with proper steps on how to deploy the nextjs app on Vercel.

Add **Deployment Guideline** at the end of the TOC and README (if it's not added already). Under this section add the **How to Deploy on Vercel** section and write the instructions here.

## Things to check before submission
- [ ] The steps provided are clear and concise enough
- [ ] No missing steps
- [ ] The app can be deployed successfully following the given steps
- [ ] The new section has been added to the TOC
- [ ] A note has been added regarding the deletion of additional files if a user is not using the Vercel for deployment (If we've to add any additional files)

> Please, copy and paste these checkpoints into the PR and mark each of them after completion.

**Comment by rafat17** [comment]
@Showrin bhai, could you please assign me this issue?
Thank you

**Comment by Showrin** [comment]
I've assigned the issue to you @rafat17. Thank you for your interest 😃
